### PR TITLE
Add test dependencies and plugin management

### PR DESCRIPTION
**Pull request by aharonha**
next version

### CODE REVIEW

**Review by artem-v — CHANGES_REQUESTED** [review]
`gatling `  is not needed, let's remove it

**Review by artem-v — COMMENTED** [review]
```xml
      <dependency>
        <groupId>io.gatling.highcharts</groupId>
        <artifactId>gatling-charts-highcharts</artifactId>
        <version>${gatling-charts-highcharts.version}</version>
        <scope>test</scope>
      </dependency>
```
Is not needed , we getting rid of galing

**Comment by dmytro-lazebnyi** [comment]
> Add **test dependencies** and plugin management

Why only test dependencies, but not also common third-party libraries such as reactor, netty, etc?
Or it will be done in another PR?

**Review by artem-v — DISMISSED** [review]

**Review by segabriel — DISMISSED** [review]

**Comment by aharonha** [comment]
@dmytro-lazebnyi If you want to add something, wait for the version to be released, create a new PR and let the @scalecube/developers the option to decide

**Review by segabriel — APPROVED** [review]

**Review by dmytro-lazebnyi — APPROVED** [review]

**Review by snripa — APPROVED** [review]

**Comment by ronenhamias** [comment]
@artem-v please write the comments on the relevant line so if its fixed we can see it outdated

**Review by omerglam — APPROVED** [review]

**Review by ronenhamias — APPROVED** [review]

**Pull request merged**
